Test Event Name
Voucher-test

Response
{
  "errorMessage": "Remote end closed connection without response",
  "errorType": "RemoteDisconnected",
  "requestId": "7eea07be-994a-4419-8992-c4bca7aa8b6f",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 84, in lambda_handler\n    with urllib.request.urlopen(req) as response:\n",
    "  File \"/var/lang/lib/python3.12/urllib/request.py\", line 215, in urlopen\n    return opener.open(url, data, timeout)\n",
    "  File \"/var/lang/lib/python3.12/urllib/request.py\", line 515, in open\n    response = self._open(req, data)\n",
    "  File \"/var/lang/lib/python3.12/urllib/request.py\", line 532, in _open\n    result = self._call_chain(self.handle_open, protocol, protocol +\n",
    "  File \"/var/lang/lib/python3.12/urllib/request.py\", line 492, in _call_chain\n    result = func(*args)\n",
    "  File \"/var/lang/lib/python3.12/urllib/request.py\", line 1392, in https_open\n    return self.do_open(http.client.HTTPSConnection, req,\n",
    "  File \"/var/lang/lib/python3.12/urllib/request.py\", line 1348, in do_open\n    r = h.getresponse()\n",
    "  File \"/var/lang/lib/python3.12/http/client.py\", line 1428, in getresponse\n    response.begin()\n",
    "  File \"/var/lang/lib/python3.12/http/client.py\", line 331, in begin\n    version, status, reason = self._read_status()\n",
    "  File \"/var/lang/lib/python3.12/http/client.py\", line 300, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\n"
  ]
}

Function Logs
START RequestId: 7eea07be-994a-4419-8992-c4bca7aa8b6f Version: $LATEST
LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
[ERROR] RemoteDisconnected: Remote end closed connection without response
